---
- name: Deploy to Tomcat
  hosts: web
  become: yes
  vars:
    tomcat_home: /opt/apache-tomcat-9.0.1
  tasks:
    - name: Copy WAR file to Tomcat
      copy:
        src: "/var/snap/jenkins/5013/workspace/MavenWebAppPipelinewithAnsible/target/MavenWebAppPipelinewithAnsible.war"
        dest: "/opt/tomcat/webapps/MavenWebAppPipelinewithAnsible.war"
        remote_src: no
    - name: Restart Tomcat
      systemd:
        name: tomcat
        state: restarted
